export const SELECT_ACTION = "SELECT_ACTION";
export const SELECT_START_GRID = "SELECT_START_GRID";
export const SELECT_END_GRID = "SELECT_END_GRID";
export const RESET_SELECTED_GRIDS = "RESET_SELECTED_GRIDS";
export const SELECT_ALGO = "SELECT_ALGO";
export const IS_HOVER = "IS_HOVER";